server:
  port: 7777
spring:
  #数据源信息，这里是阿里云的数据库，大家不用改了
  datasource:
    #后缀是用来确定时区编码方式的，不用管。下面的账号和密码，都不要改，直接就可以运行的
    url: jdbc:mysql://rm-bp19uy25263w6i51lbo.mysql.rds.aliyuncs.com:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xuruihang
    password: Xrh_180902
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志，用于输出mysql语句的
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 全局配置
  global-config:
    db-config:
      #逻辑删除，就是没有从数据库中真实的删除，只是改变了delflag这个字段值，把它变为了0或者1;
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      #这个全局策略可以保证所有对表的增加操作，id自增
      id-type: auto
oss:
  accessKey: daddasd
  secretKey: weqeqwe
  bucket: sg_blog